CREATE SCHEMA SA;


	CREATE TABLE SA.FLIGHT
	(FLIGHT_ID CHAR(6) NOT NULL CONSTRAINT F_PK PRIMARY KEY,
	DESTINATION VARCHAR(100));

	CREATE TABLE SA.FLIGHT_DETAILS
	(FLIGHT_DET_ID CHAR(6) NOT NULL CONSTRAINT FID_PK PRIMARY KEY,
	FLIGHT_CD CHAR(6) NOT NULL,
	ECONOMIC INT,
	BUSINESS INT, 
	FIRST_CLASS INT,
	DEPARTURE_TIME INT
	);

	
ALTER TABLE SA.FLIGHT_DETAILS  
       ADD CONSTRAINT FLIGHT_FK 
       FOREIGN KEY (FLIGHT_CD)  
       REFERENCES SA.FLIGHT(FLIGHT_ID);
       
       
	INSERT INTO SA.FLIGHT
	VALUES('mx', 'mexico');
	INSERT INTO SA.FLIGHT
	VALUES('us','usa');
	INSERT INTO SA.FLIGHT
	VALUES('br','brasil');
	INSERT INTO SA.FLIGHT
	VALUES('fr','france');
	
	INSERT INTO SA.FLIGHT_DETAILS(FLIGHT_DET_ID, FLIGHT_CD, ECONOMIC, BUSINESS, FIRST_CLASS, DEPARTURE_TIME) 
	VALUES('mx1', 'mx', 50,20,10,1800);
	INSERT INTO SA.FLIGHT_DETAILS(FLIGHT_DET_ID, FLIGHT_CD, ECONOMIC, BUSINESS, FIRST_CLASS, DEPARTURE_TIME) 
	VALUES('mx2','mx',30,40,15,1900);
	INSERT INTO SA.FLIGHT_DETAILS(FLIGHT_DET_ID, FLIGHT_CD, ECONOMIC, BUSINESS, FIRST_CLASS, DEPARTURE_TIME) 
	VALUES('mx3','mx',10,26,80,1700);